
name: Build and Deploy to Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-microservices:
    runs-on: ubuntu-latest

  

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # Step 3: Build the project using Maven
    - name: Build with Maven
      run: mvn --projects :accounts clean install

    # Step 4: Deploy to Heroku
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_APP_NAME_ACCOUNTS: ${{ secrets.HEROKU_APP_NAME_ACCOUNTS }}
      run: |
        git config --global user.email "tiziano.riccioli@gmail.com"
        git config --global user.name "tizzy273"
      
        accounts=${{ secrets.HEROKU_APP_NAME_ACCOUNTS }}

        git remote add heroku https://git.heroku.com/app-accounts.git

        git subtree split --prefix=app-accounts -b deploy-branch
      
        git add .
        git commit -m "Deploy to Heroku from GitHub Actions" || echo "No changes to commit"

        git subtree split --prefix=app-accounts -b deploy-branch
        
        git push --force heroku deploy-branch:refs/heads/main
